version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    # image field added so remote build produces known image name
    image: local/3tier-backend:latest
    build: ./backend
    container_name: flask_app
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "5000:5000"
    depends_on:
      - db

  nginx:
    image: local/3tier-nginx:latest
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
